
staging:
  profile: ~
  whoami:  asf-staging

publish:
  whoami:  asf-site

github:
  description: "Apache Accumulo Website"
  homepage: https://accumulo.apache.org/
  labels:
    - accumulo
    - big-data
    - asf-site
  features:
    wiki: false
    issues: true
    projects: true

jekyll:
  whoami: master
  target: asf-staging

